DROP DATABASE IF EXISTS aaa ;
CREATE DATABASE aaa ;
USE aaa ;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS idpass;
CREATE TABLE  idpass (
	id varchar(255) DEFAULT NULL AUTO_INCREMENT ,
	pwd varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO member VALUES('123','456') ;